### PR TITLE
Feature calculator

### PR DESCRIPTION
**Pull request by Fathima07**
I added celcius calculator with typescript

### CODE REVIEW

**Comment by mbovel** [comment]
Nice!

Minor problem: the conversion should work in both directions: the Celsius `<input>` should also automatically be updated when the Fahrenheit `<input>` changes.

**Review by mbovel — CHANGES_REQUESTED** [review]
Nice!

Minor problem: the conversion should work in both directions: the Celsius <input> should also automatically be updated when the Fahrenheit <input> changes.

**Comment by Fathima07** [comment]
I have fixed it Sir, Please check

**Review by mbovel — APPROVED** [review]
Good, seems to work now! 😃

**Comment by mbovel** [comment]
As there are a few extra commits in this PR, you might want to merge with squashing:

image

This will group the 5 commits into one.

**Comment by Fathima07** [comment]
Done sir merged like that, Thank you

**Pull request merged**
